---
title: "Market Analysis on US Commodities and Stocks"
author: "Alex Pugh"
format:
  revealjs:
    theme: serif
    transition: concave 
    embed-resources: true
    slide-number: true
 #   chalkboard: 
  #    buttons: false
    preview-links: auto
   # logo: images/quarto.png
  #  css: styles.css
   # footer: "UConn Intro to Data Science: STAT 3255/5255"
    #code-fold: 
execute:
  warning: false
  error: false
output:
  quarto::quarto_presentation:
    scrollable: true
---

## Outline {.scrollable} 
- Background Information
- Data Description and Cleaning
- Hypothesis Testing
- Time Series Analysis 
- Discussion and Conclusion

# Background Information

## Project Info {.scrollable}
- Chosen Data: United States stocks and commodities data for every trading day from January 2, 2020 to February 1, 2024
- Relevant Variables: 
  - 'Date', 'Natural_Gas_Price', 'Netflix_Volume', ...
- Aims: Determine if market trends are predictable due to season patterns

## Relevant Works
<!-- - <https://www.degruyter.com/document/doi/10.1515/jqas-2020-0017/html>: 
  - Focuses on identifying pass coverage types
- <https://heinonline.org/HOL/LandingPage?handle=hein.journals/frdipm18&div=31&id=&pag>: 
  - Argues against league-wide defensive uniformity
- <https://www.degruyter.com/document/doi/10.1515/jqas-2019-0052/html>: 
  - Evaluates quarterbacks' performance through CPOE -->

# Data Description and Cleaning

## Approach {.scrollable}
- Fix data structure
- Observe missing variable statistics and explain their omission
- Observe descriptive statistics of numerical variables
- Plot line graphs of numerical variables over time


## Data Description {.scrollable}
- This data is from kaggle, uploaded by Muhammad Ehsan. 
- Each row of the csv is a stock, commodity, or cryptocurrency volume or price data point. 
- Each row is taken from a single trading day, with no days repeating. 
- The temporal data runs from January 1, 2020 to February 2, 2024.

## Data Cleaning {.scrollable}
```{python}
#| echo: false
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None) 
df = pd.read_csv("US_Stock_Data.csv")
```

Looking at the date format of our data, we immediately notice an issue:

- The format of the date of the second data point is:

```{python}
df['Date'][1]
```

- The format of the date of the third data point is:

```{python}
df['Date'][2]
```

Both dates are in a day, month, year format. However, 